version: '3.7'

services:
    wordpress:
        build: ./docker-wp
        ports:
            - "8888:80"
        depends_on:
            - db
        links:
            - db
        volumes:
            - ./../src:/var/www/html
    db:
        build: ./docker-mysql
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: myblog
